version: 2

models:
  - name: fct_events_daily
    description: "Daily event and engagement metrics derived from stg_events."
    columns:
      - name: date_day
        description: "UTC day derived from event_ts."
        tests:
          - not_null
          - unique
      - name: events
        description: "Total number of events on the day."
        tests:
          - not_null
      - name: dau
        description: "Daily active users (distinct non-null user_id)."
        tests:
          - not_null
      - name: late_events
        description: "Count of events where received_ts > event_ts."
        tests:
          - not_null


  - name: fct_billing_daily
    description: "Daily billing start metrics by plan derived from stg_billing."
    columns:
      - name: date_day
        description: "Billing date (day grain)."
        tests:
          - not_null
      - name: plan_id
        description: "Plan identifier (e.g., pro)."
        tests:
          - not_null
      - name: starts
        description: "Count of billing start events on the day for the plan."
        tests:
          - not_null
      - name: new_paid_users
        description: "Distinct users with a start event on the day for the plan."
        tests:
          - not_null


  - name: fct_subscriptions_daily
    description: "Daily subscription state per user derived from billing events (start/upgrade/cancel)."
    columns:
      - name: date_day
        description: "Day grain of subscription state."
        tests:
          - not_null
      - name: user_id
        description: "User identifier."
        tests:
          - not_null
      - name: is_active
        description: "Whether the user has an active subscription on the day."
        tests:
          - not_null
      - name: plan_id
        description: "Active plan_id on the day (null if inactive)."

    

  - name: gold_churn_labels_daily
    description: "Daily churn labels: churn_7d=1 if active today and inactive for the next 7 days."
    columns:
      - name: date_day
        tests: [not_null]
      - name: user_id
        tests: [not_null]
      - name: churn_7d
        description: "Binary churn label (0/1)."
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]


  - name: gold_user_features_daily
    description: "Model-ready daily user feature table joined to churn labels."
    columns:
      - name: date_day
        tests: [not_null]
      - name: user_id
        tests: [not_null]
      - name: churn_7d
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]
      - name: late_rate_7d
        description: "Late events / total events in last 7 days."